version: 2.1

executors:
  my-executor:
    working_directory: /tmp/repo

orbs:
  github-cli: circleci/github-cli@2.2.0

jobs:
  trigger_release:
    executor: my-executor
    machine: true
    steps:
      - github-cli/setup
      - run:
          name: Trigger release
          command: |
            gh api repos/${CIRCLE_PROJECT_USERNAME}/${TARGET_REPO}/releases \
              -X POST \
              -f tag_name=${CIRCLE_PROJECT_REPONAME}${CIRCLE_TAG} \
              -f target_commitish=main \
              -f name=${CIRCLE_PROJECT_REPONAME}${CIRCLE_TAG} \
              -f body="Release ${CIRCLE_PROJECT_REPONAME}${CIRCLE_TAG} from ${CIRCLE_PROJECT_REPONAME}" \
              -f draft=false \
              -f prerelease=false

workflows:
  release-flow:
    jobs:
      - trigger_release:
          context: default
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/